enum ButtonCode_t
{
    BUTTON_CODE_INVALID = -1,
    BUTTON_CODE_NONE = 0,

    KEY_FIRST = 0,

    KEY_NONE = KEY_FIRST,
    KEY_0,
    KEY_1,
    KEY_2,
    KEY_3,
    KEY_4,
    KEY_5,
    KEY_6,
    KEY_7,
    KEY_8,
    KEY_9,
    KEY_A,
    KEY_B,
    KEY_C,
    KEY_D,
    KEY_E,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_I,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_M,
    KEY_N,
    KEY_O,
    KEY_P,
    KEY_Q,
    KEY_R,
    KEY_S,
    KEY_T,
    KEY_U,
    KEY_V,
    KEY_W,
    KEY_X,
    KEY_Y,
    KEY_Z,
    KEY_PAD_0,
    KEY_PAD_1,
    KEY_PAD_2,
    KEY_PAD_3,
    KEY_PAD_4,
    KEY_PAD_5,
    KEY_PAD_6,
    KEY_PAD_7,
    KEY_PAD_8,
    KEY_PAD_9,
    KEY_PAD_DIVIDE,
    KEY_PAD_MULTIPLY,
    KEY_PAD_MINUS,
    KEY_PAD_PLUS,
    KEY_PAD_ENTER,
    KEY_PAD_DECIMAL,
    KEY_LBRACKET,
    KEY_RBRACKET,
    KEY_SEMICOLON,
    KEY_APOSTROPHE,
    KEY_BACKQUOTE,
    KEY_COMMA,
    KEY_PERIOD,
    KEY_SLASH,
    KEY_BACKSLASH,
    KEY_MINUS,
    KEY_EQUAL,
    KEY_ENTER,
    KEY_SPACE,
    KEY_BACKSPACE,
    KEY_TAB,
    KEY_CAPSLOCK,
    KEY_NUMLOCK,
    KEY_ESCAPE,
    KEY_SCROLLLOCK,
    KEY_INSERT,
    KEY_DELETE,
    KEY_HOME,
    KEY_END,
    KEY_PAGEUP,
    KEY_PAGEDOWN,
    KEY_BREAK,
    KEY_LSHIFT,
    KEY_RSHIFT,
    KEY_LALT,
    KEY_RALT,
    KEY_LCONTROL,
    KEY_RCONTROL,
    KEY_LWIN,
    KEY_RWIN,
    KEY_APP,
    KEY_UP,
    KEY_LEFT,
    KEY_DOWN,
    KEY_RIGHT,
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_F11,
    KEY_F12,
    KEY_CAPSLOCKTOGGLE,
    KEY_NUMLOCKTOGGLE,
    KEY_SCROLLLOCKTOGGLE,

    KEY_LAST = KEY_SCROLLLOCKTOGGLE,
    KEY_COUNT = KEY_LAST - KEY_FIRST + 1,

    // Mouse
    MOUSE_FIRST = KEY_LAST + 2,

    MOUSE_LEFT = MOUSE_FIRST,
    MOUSE_RIGHT = 109,
    MOUSE_MIDDLE,
    MOUSE_4,
    MOUSE_5,
    MOUSE_WHEEL_UP,   // A fake button which is 'pressed' and 'released' when the wheel is moved up
    MOUSE_WHEEL_DOWN, // A fake button which is 'pressed' and 'released' when the wheel is moved down

    MOUSE_LAST = MOUSE_WHEEL_DOWN,
    MOUSE_COUNT = MOUSE_LAST - MOUSE_FIRST + 1,

    KEY_XBUTTON_A = 115,        // 115
    KEY_XBUTTON_B,              // 116
    KEY_XBUTTON_X,              // 117
    KEY_XBUTTON_Y,              // 118
    KEY_XBUTTON_LEFT_SHOULDER,  // 119
    KEY_XBUTTON_RIGHT_SHOULDER, // 120
    KEY_XBUTTON_BACK,
    KEY_XBUTTON_START,
    KEY_XBUTTON_STICK1,
    KEY_XBUTTON_STICK2,

    KEY_XSTICK1_RIGHT,          // XAXIS POSITIVE
    KEY_XSTICK1_LEFT = 123,     // XAXIS NEGATIVE             //L3-123
    KEY_XSTICK1_DOWN,           // YAXIS POSITIVE             //R3-124
    KEY_XSTICK1_UP,             // YAXIS NEGATIVE
    KEY_XBUTTON_LTRIGGER = 126, // ZAXIS POSITIVE             //126
    KEY_XBUTTON_RTRIGGER = 127, // ZAXIS NEGATIVE             //127
    KEY_XSTICK2_RIGHT,          // UAXIS POSITIVE
    KEY_XSTICK2_LEFT,           // UAXIS NEGATIVE
    KEY_XSTICK2_DOWN,           // VAXIS POSITIVE
    KEY_XSTICK2_UP,             // VAXIS NEGATIVE
};
/*[115] = "KEY_XBUTTON_A",
    [116] = "KEY_XBUTTON_B",
    [117] = "KEY_XBUTTON_X",
    [118] = "KEY_XBUTTON_Y",
    [119] = "KEY_XBUTTON_BLACK",
    [120] = "KEY_XBUTTON_WHITE",
    [121] = "KEY_XBUTTON_LTRIGGER",
    [122] = "KEY_XBUTTON_RTRIGGER",
    [123] = "KEY_XSTICK1_UP",
    [124] = "KEY_XSTICK1_DOWN",
    [125] = "KEY_XSTICK1_LEFT",
    [126] = "KEY_XSTICK1_RIGHT",
    [127] = "KEY_XSTICK2_UP",
    [128] = "KEY_XSTICK2_DOWN",
    [129] = "KEY_XSTICK2_LEFT",
*/